apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/michal5520pl/gitops-inzynierka-flux.git
    path: overlays/flux-instances
    targetRevision: main
  destination:
    name: "in-cluster"
    namespace: flux-system
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
