apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flux-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: flux-operator
    repoURL: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator
    targetRevision: 0.48.0
  destination:
    name: "in-cluster"
    namespace: flux-system
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
