---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openstack-drivers
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          - app: cinder-csi
            chart: openstack-cinder-csi
          - app: manila-csi
            chart: openstack-manila-csi
  template:
    metadata:
      name: '{{.app}}'
    spec:
      project: openstack
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          enabled: true
          selfHeal: true
      ignoreDifferences:
        - group: rbac.authorization.k8s.io
          kind: ClusterRole
          name: manila-csi-openstack-manila-csi-controllerplugin
          jsonPointers:
            - /roles
        - group: rbac.authorization.k8s.io
          kind: ClusterRole
          name: manila-csi-openstack-manila-csi-nodeplugin
          jsonPointers:
            - /roles
      source:
        chart: "{{.chart}}"
        repoURL: https://kubernetes.github.io/cloud-provider-openstack
        targetRevision: 2.35.0
        helm:
          valuesObject: # these values will be used only by cinder-csi-plugin, because manila-csi-plugin does not use these variables
            secret:
              enabled: true
              create: false
              hostMount: false
              name: cinder-csi-cloud-config
            storageClass:
              delete:
                isDefault: true
      destination:
        name: in-cluster
        namespace: "openstack-{{.app}}"
...
